# Generated by Django 2.1.5 on 2019-02-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-modified'], 'verbose_name_plural': 'Articles'},
        ),
    ]
