# Generated by Django 2.1.5 on 2019-01-08 21:11

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190108_2102'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='entry',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
