# Generated by Django 2.1.5 on 2019-01-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190109_2144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-modified'], 'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='body',
            field=models.TextField(default='some text', max_length=1000),
        ),
    ]
